### ISSUE TITLE
I don't know how the ex_data_table works for a remote database relop operations tree

### ISSUE THREAD

**Issue by konny0201** [WinVector/rqdatatable#2]
vv_cid_day_table=db_td(con_dm_result,'vv_cid_day')
vv_bid_day_info_tree <- vv_cid_day_table %.>% select_rows_nse(.,date>=startday_parameter & date<=endday_parameter ) %>.% project_nse(.,groupby = c('date','bid'),vv:=sum(vv)) %.>% extend_nse(.,group_bid:=ifelse(bid==2|bid==102,2,ifelse(bid==4|bid==104,4,ifelse(bid==5|bid==105,5,bid)))) %.>% project_nse(.,groupby=c('date','group_bid'),vv_commercial:=max(vv),vv_nocommercial:=min(vv) ) 
e=ex_data_table(vv_bid_day_info_tree,tables=list(vv_cid_day_table=vv_cid_day_table) )[]

**Comment by JohnMount** [comment]
ex_data_table() is only for local data.  I'll improve the error msgs.

**Comment by konny0201** [comment]
Thank you~In this case can I use the wrapr::execute_parallel() function?

**Comment by JohnMount** [comment]
Combining wrapr::execute_parallel() with remote tables is not recommended and not a scenario we are supporting.  The issue is each worker would need a different connection the remote database (such connections should not be compared over sockets) and likely the remote system would not handle well many connections from the same R to the same tables anyway.
